### ISSUE TITLE
ListZipper flips elements on sides?

### ISSUE THREAD

**Issue by AlexeyRaga** [NICTA/course#139]
-- >>> moveLeftLoop (zipper [] 1 [2,3,4])

By the tests the result is expected to be 

    -- [3,2,1] >4< []

But shouldn't it be 

    -- [1,2,3] >4< []

instead? 

As far A I understand, the "cursor" is supposed to be moved, but the structure should be preserved.

Otherwise the following equation fails:

    (toList lz) == (toList $ moveLeftLoop lz)

Which is a bit strange. Or is it expected?

**Comment by markhibberd** [comment]
@AlexeyRaga I think you are just being thrown off by how the lefts are stored. They are stored (and displayed) in reverse order. This is because you need to be able to move 1 to the left in `O(1)` which you can only do if the element you need is at the head of the lefts list. Does the equation you state actually fail? By the other things you have shown I expect it to be `True`. i.e.

`[3,2,1] >4< []` should unwind to `[1, 2, 3, 4]`

In the same way that:

`[] >1< [2, 3, 4]` should unwind to `[1, 2, 3, 4]`.

**Comment by AlexeyRaga** [comment]
Ah, I haven't noticed that the left side is stored in reverse order, makes sense, thanks.
