### ISSUE TITLE
Why is this implementation not correct?

### ISSUE THREAD

**Issue by dorafmon** [NICTA/course#150]
So I am trying to implement the ``reverse" function in ``List.hs" and I have the following implementation:

```
reverse ::
  List a
  -> List a
reverse Nil = Nil
reverse (x :. xs) = let l = (reverse xs) in l ++ (x:.Nil)
```

But it seems that it have a infinite loop in it, could you enlighten me why is that the case?

**Comment by eccstartup** [comment]
I think you would like to post also the implementation of `++`.

**Comment by eccstartup** [comment]
And how you run your code with `reverse`.

**Comment by mulderr** [comment]
Your implementation is fine (almost). It *will* produce the correct result. Eventually.

The "problem" is this test:

    take 1 (reverse (reverse largeList))

where `largeList` is defined to have 50000 elements. I pasted your implementation into `List.hs` and run it in ghci using my own implementation of `++` like this:

    reverse largeList

I gave up after about 10 mins but the point is it is producing the correct result. Just... slowly.

I should very much like to see a detailed explanation of why that is myself. What I can tell you:
* your implementation causes 78% of time to be wasted in GC
* `++` is not free in terms of performance, you should consider using `:.` instead
* whenever you have a function that does something to every element of a list it's probably a fold

So, can you instead try and implement reverse as a fold not using `++`?

**Comment by fizruk** [comment]
Basically the solution presented by @dorafmon has time complexity **O(n²)** which is why it performs slowly on large lists. To see that, consider the second equation is the `reverse` definition:

```haskell
reverse (x :. xs) = let l = (reverse xs) in l ++ (x:.Nil)
```

To `reverse` a non-empty list we have to
1. `reverse` its tail;
2. append the first element of the input list to the end of the reversed tail.

To append an element to the end of a list we have to traverse the whole list to the end, which is **O(m)** if **m** is the length of the list. We'll need this fact later.

Now, since we `reverse` recursively and we take one element from the list each time we recurse, there will be exactly **n** recursive calls and exactly **n** appends.
The innermost recursive call will deal with the empty list. The next one will append one element to the end of the reversed empty list. The second one will append one element to the end of that and so on:

```
reverse [1, 2, 3 .. n]
= reverse [2, 3 .. n] ++ [1]
= (reverse [3 .. n] ++ [2]) ++ [1]
= (((..(reverse [] ++ [n]) .. ) ++ [3]) ++ [2]) ++ [1]
= ((..([] ++ [n]) .. ) ++ [3]) ++ [2]) ++ [1]
= (((..([n] ++ [n - 1]) .. ) ++ [3]) ++ [2]) ++ [1]
= ([n .. 3] ++ [2]) ++ [1]
= [n .. 3, 2] ++ [1]
= [n .. 3, 2, 1]
```

Now we can see that every next append takes a list which is one element longer than was given to the previous append. The first append will have an empty list as its input while the last (**n**th) append will have a list of **n – 1** elements to traverse. When we sum up those lengths we get quadratic time complexity of the overall solution:

```
0 + 1 + 2 + ... + (n - 2) + (n - 1)
= (0 + (n - 1)) * n / 2
= n * (n - 1) / 2
= O(n²)
```

Aside from time complexity there is also one other thing that makes the solution slow: `List a` is not a subject to [fusion](http://stackoverflow.com/questions/578063/what-is-haskells-stream-fusion) like `[a]`, so every intermediate `List` is created in memory and is garbage collected after. This is why @mulderr witnessed 78% of time wasted in GC. Note that the overall memory spent on these intermediate lists is also **O(n²)** (can you figure out why?).

**Comment by eccstartup** [comment]
I agree. It is very slow, but not an infinite loop.

**Comment by dorafmon** [comment]
Thanks guys, now I understand this issue better.
